### PR TITLE
Refactor Runtime

### PR DESCRIPTION
**Pull request by dr-orlovsky**
~~`Runtime` is misleading since there might be many different runtimes for different purposes. This one is quite simple one - it just reads and writes wallet to a file.~~

~~To use it one will also need an update in RGB wallet: https://github.com/RGB-WG/rgb/pull/216~~

~~@zoedberg there is nothing to review actually, I set you as a reviewer to inform about the name change if you are using this type (I assume you are not).~~

UPD: I found a bug in the implementation of `StoredWallet` which doesn't automatically save the data upon modification. As a part of the solution, I have refactored `StoredWallet` into `Wallet` itself.

UPD2: I ended up with some larger refactoring due to the discovery of a bug when the wallet data are not always saved to the disk. Thus, I have refactored all FS-related workflows to ensure the data are always saved. As a side-effect, I got rid of a few types and traits which became redundant, thus the APIs and namings have become clearer and simpler.

This PR has two counterparts:
- https://github.com/RGB-WG/rgb-std/pull/234
- https://github.com/RGB-WG/rgb/pull/216

### CODE REVIEW

**Comment by zoedberg** [comment]
@dr-orlovsky I agree that the term `Runtime` is misleading since it's already used. But the term `StoredWallet` is also already used in rgb (https://github.com/RGB-WG/rgb/blob/master/src/store.rs#L130), so I think it's better to find another name

**Comment by dr-orlovsky** [comment]
Yes, that was a thought to get things in line with RGB naming. Both are StoredWallets - they are differentiated by their crate prefix. Users of one will not use the other - and wise verse

**Comment by zoedberg** [comment]
> Users of one will not use the other - and wise verse

I don't think this is the case. Check the [integration tests PR](https://github.com/RGB-WG/rgb-integration-tests/pull/2) where we use both the `bpwallet::Runtime` and `rgb::StoredWallet`

**Comment by dr-orlovsky** [comment]
I ended up with some larger refactoring due to discovery of a bug when the wallet data are not always saved to the disk. Thus, I have refactored all FS-related workflows to ensure that the data are always saved. As a side-effect, I got rid of few types and traits which become redundant, thus the APIs and namings have become clearer and simpler.

This PR has two counterparts:
- https://github.com/RGB-WG/rgb-std/pull/234
- https://github.com/RGB-WG/rgb/pull/216

**Comment by zoedberg** [comment]
it seems there's an error with features usage:
```
error[E0433]: failed to resolve: could not find `cli` in `bpwallet`
  --> rgb/src/errors.rs:88:18
   |
88 |     Bp(bpwallet::cli::ExecError),
   |                  ^^^ could not find `cli` in `bpwallet`
   |
note: found an item that was configured out
  --> /mnt/dmc/zoe/work/bitfinex/rgb-integration-tests/bp-wallet/src/lib.rs:42:9
   |
42 | pub mod cli;
   |         ^^^
   = note: the item is gated behind the `cli` feature

For more information about this error, try `rustc --explain E0433`.
error: could not compile `rgb-runtime` (lib) due to 1 previous error
```
by adding the `cli` feature to bp-wallet this error disappears, but I think we need to fix feature gates

**Review by zoedberg — APPROVED** [review]
tACK 30ae979f658b5b4643352387a3e5e36f8f817098

**Pull request merged**
