### PR TITLE
fix bug: esplora negative balance

### PR DESCRIPTION
**Pull request by eauxxs**
Because explora's [API document](https://github.com/Blockstream/esplora/blob/master/API.md#get-scripthashhashtxs) describes that an address can obtain up to 50 mempool + 25 confirmed results in one request, so if the returned results are 25 or more, we should request again to obtain more. Otherwise, the final balance resulting in the calculation may be a negative number.

### CODE REVIEW

**Comment by eauxxs** [comment]
https://github.com/RGB-WG/rgb/issues/176

**Review by dr-orlovsky — APPROVED** [review]
LGTM. Will wait for @zoedberg review since she has more experience with indexers

**Comment by zoedberg** [comment]
I confirm this should fix the balance calculation in case the user received a lot of TXs on the same script. I'm not sure that this fixes https://github.com/RGB-WG/rgb/issues/176 though, because in the sandbox (which is the tool used when that issue has been found) we don't do many TXs and we always create new addresses before requesting more funds.

**Review by dr-orlovsky — APPROVED** [review]
ACK dd7401a198f4b44fc5705de30ff3359d6f17b36c

**Comment by eauxxs** [comment]
@zoedberg It is exactly what you said. I fixed this bug not because of the issue. I encountered this problem during my testing. And I saw that his issue description is exactly the same as mine. I downloaded his attachment and found that there are only two tx in it. Maybe his situation is different from mine. He can try to pull this PR and see if it can be fixed. Thank you very much for your review.

**Pull request merged**
